### ISSUE TITLE
Does not connect directly to BBSP?

### ISSUE THREAD

**Issue by notchris** [mage2pro/blackbaud-netcommunity#1]
Looking at the source, this module seems to utilize NetCommunity SSO, but does not create a transaction with BBSP, which NetCommunity mandates for secure transactions. Please correct me if I'm wrong.

**Comment by dmitrii-fediuk** [comment]
My software product is implemented according with the **[Blackbaud NetCommunity 7.1 Single Sign-on Overview Guide (2017-01-24)](https://mage2.pro/t/topic/3696)**.

**Comment by notchris** [comment]
But that does not connect directly to BBSP, which NetCommunity uses to process transactions.

**Comment by dmitrii-fediuk** [comment]
I do not play in letters and abbreviations, I just do working software products. It works. It is implemented according with the Blackbaud NetCommunity 7.1 Single Sign-on Overview Guide (2017-01-24).

**Comment by notchris** [comment]
I'm just letting you know that SSO may work, but can users purchase NetCommunity products and checkout without going to the NetCommunity site? Also, no need to be rude, just trying to clarify what you've done!

Update: I've confirmed with Blackbaud that it is impossible to use the NetCommunity payment system from an external source, even with SSO.
